import React, { useState } from 'react';
import { AuthLayout } from '../../components/AuthLayout';
import { useAuth } from '../../hooks/useAuth';
import './auth.css';

export default function SignUpPage() {
  const { signUp } = useAuth();
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [sent, setSent] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(''); setBusy(true); try { const invite = new URLSearchParams(window.location.search).get('invite'); window.localStorage.setItem('rm-signup-email', email); if (invite) window.localStorage.setItem('rm-invite-token', invite); const result = await signUp({ name, email, password, inviteToken: invite }); if (result.session) window.location.replace(invite ? `/join/${encodeURIComponent(invite)}` : '/app'); else setSent(true); } catch (err) { setError(err.message || 'Could not create your account'); } finally { setBusy(false); } };
  if (sent) { const invite = new URLSearchParams(window.location.search).get('invite'); return <AuthLayout><h1>Check your inbox.</h1><p className="rm-auth-sub">We sent a confirmation link to <strong>{email}</strong>.</p><a className="rm-auth-primary-btn" href={invite ? `/signin?invite=${encodeURIComponent(invite)}` : '/signin'}>Go to sign in</a><p className="rm-auth-legal">Didn’t get it? Check spam, then try signing up again.</p></AuthLayout>; }
  const invite = new URLSearchParams(window.location.search).get('invite');
  return <AuthLayout><h1>Make the flat calmer.</h1><p className="rm-auth-sub">Create your free RoomMate account.</p><form onSubmit={submit}><label className="rm-auth-label" htmlFor="signup-name">Name</label><input id="signup-name" className="rm-auth-field" autoComplete="name" placeholder="Your name" value={name} onChange={(e) => setName(e.target.value)} required /><label className="rm-auth-label" htmlFor="signup-email">Email</label><input id="signup-email" className="rm-auth-field" type="email" autoComplete="email" placeholder="you@example.com" value={email} onChange={(e) => setEmail(e.target.value)} required /><label className="rm-auth-label" htmlFor="signup-password">Password</label><input id="signup-password" className="rm-auth-field" type="password" autoComplete="new-password" minLength="8" placeholder="At least 8 characters" value={password} onChange={(e) => setPassword(e.target.value)} required />{error && <p className="rm-auth-error" role="alert">{error}</p>}<button className="rm-auth-primary-btn" type="submit" disabled={busy}>{busy ? 'Creating account…' : 'Create account'}</button></form><p className="rm-auth-legal">Already have an account? <a href={invite ? `/signin?invite=${encodeURIComponent(invite)}` : '/signin'}>Sign in</a></p></AuthLayout>;
}
